// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      default:
        throw webConfig;
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTSfAcFlRkYdBkdHQxqYyjaY5_IjN4z1c',
    appId: '1:1064312758567:ios:15cb9e296c38967a988902',
    messagingSenderId: '1064312758567',
    projectId: 'health-horizon-5577',
    databaseURL: 'https://health-horizon-5577-default-rtdb.firebaseio.com',
    storageBucket: 'health-horizon-5577.appspot.com',
    androidClientId:
        '1064312758567-sfhce1jnneiufsfna429ao030h9l0cbq.apps.googleusercontent.com',
    iosClientId:
        '1064312758567-ppn3dk0mdjnbeu29eenu5s3m7oichvr3.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthHorizonWebos',
  );
  static const webConfig = FirebaseOptions(
      apiKey: "AIzaSyD8aH6CaS6O3Hx1YMuJWwnVFu5qiv2gGV0",
      authDomain: "health-horizon-5577.firebaseapp.com",
      databaseURL: "https://health-horizon-5577-default-rtdb.firebaseio.com",
      projectId: "health-horizon-5577",
      storageBucket: "health-horizon-5577.appspot.com",
      messagingSenderId: "1064312758567",
      appId: "1:1064312758567:web:518846f108f08128988902");
}
